/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.col-sm-6[_ngcontent-%COMP%] {\r\n    padding-top: 15px;\r\n    padding-bottom: 15px;\r\n}'];
//# sourceMappingURL=changePassword.component.css.shim.ngstyle.js.map