/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.cho-fil[_ngcontent-%COMP%] {\n  padding: 15px;\n  max-height: 345px;\n  overflow: auto;\n}\n.cho-filcnt[_ngcontent-%COMP%] {\n  position:relative;\n  width: 50%;\n}\n.cho-fil[_ngcontent-%COMP%]   button[_ngcontent-%COMP%] {\n  color: #0A2F87;\n  padding: 0;\n  background: #ccc;\n  border: 1px dashed #0A2F87;\n}\n.cho-fil[_ngcontent-%COMP%]   input[_ngcontent-%COMP%] {\n  width: 100%;\n  padding: 30px !important;\n  float: left;\n  margin: 0 !important;\n}\n.cho-fil[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\n  width: 100%;\n  height: auto;\n}\n.sbmt-pic[_ngcontent-%COMP%] {\n  padding: 15px;\n}\n.imgrw[_ngcontent-%COMP%] {\n  float: left;\n}\n.imgrw-cnt[_ngcontent-%COMP%] {\n  float: left;\n  overflow: hidden;\n  position: relative;\n  margin: 6px;\n  padding: 0 !important;\n  display: flex;\n  justify-content: center;\n}\n.imgrw[_ngcontent-%COMP%]   td[_ngcontent-%COMP%] {\n    padding: 0 !important;\n}\n.imgrw-cnt[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\n  height: 100%;\n  width: auto;\n  max-width: none;\n  flex: none;\n}\n.dlt-btn[_ngcontent-%COMP%] {\n  position: absolute;\n  top: 0 !important;\n  right: 0 !important;\n  background-color: #000000 !important;\n  color: #fff !important;\n  border: none !important;\n  outline: none !important;\n  padding: 10px !important\n}\n.rec-sze[_ngcontent-%COMP%] {\n  font-size: 10px !important;\n  color: #999999 !important;\n}\n\n@media screen and (min-width:768px) {\n\n.imgrw-cnt[_ngcontent-%COMP%] {\n  height: 150px;\n  width: 150px;\n}\n}\n\n@media screen and (max-width:767px) {\n\n.imgrw-cnt[_ngcontent-%COMP%] {\n  height: 115px;\n  width: 115px;\n}\n}'];
//# sourceMappingURL=form.component.css.shim.ngstyle.js.map