/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.phyto-topnav[_ngcontent-%COMP%] {\n    height: 100% !important;\n    background-color: #efe9df !important;\n}\n.done[_ngcontent-%COMP%], .pas-done[_ngcontent-%COMP%] {\n    margin: 15px 0px;\n}\n.login-form[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\n    margin-bottom: 30px;\n}\n.message[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    color: #999999;\n    font-size: 12px;\n}'];
//# sourceMappingURL=login.component.css.shim.ngstyle.js.map