/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.phyto-topnav[_ngcontent-%COMP%] {\n    height: 100% !important;\n    background-color: #efe9df !important;\n}\n.done[_ngcontent-%COMP%], .pas-done[_ngcontent-%COMP%] {\n    margin: 15px 0px;\n}\n.login-form[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\n    margin-bottom: 30px;\n}\n.message[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    color: #999999;\n    font-size: 12px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FsYW4vYXBwL2FsZXMvc2Fsb24vc3JjL2FwcC91c2VyL2xvZ2luL2xvZ2luLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYWxhbi9hcHAvYWxlcy9zYWxvbi9zcmMvYXBwL3VzZXIvbG9naW4vbG9naW4uY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
