/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/productBatch/productBatch.module';
import * as import2 from '@angular/router';
import * as import3 from '../../../../src/app/productBatch/productBatchRouting.module';
import * as import4 from '@angular/common';
import * as import5 from '@angular/forms';
import * as import6 from '@angular/material';
import * as import7 from 'ng2-pagination/dist/ng2-pagination';
import * as import8 from 'ng2-pagination/dist/pagination.service';
import * as import9 from '../../../../src/app/productBatch/productBatch.service';
import * as import10 from './productBatchsAdmin.component.ngfactory';
import * as import11 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as import12 from '@angular/http';
import * as import13 from '@angular/platform-browser';
import * as import14 from '../../../../src/app/errorHandler/error.service';
import * as import15 from 'ng2-toastr/src/toast-manager';
import * as import16 from '../../../../src/app/auth/auth.service';
import * as import17 from '../../../../src/app/productBatch/productBatchsAdmin.component';
import * as import18 from '../../../../src/app/admin/services/adminGuard';
class ProductBatchModuleInjector extends import0.ɵNgModuleInjector<import1.ProductBatchModule> {
  _RouterModule_0:import2.RouterModule;
  _ProductBatchRouting_1:import3.ProductBatchRouting;
  _CommonModule_2:import4.CommonModule;
  _ɵba_3:import5.ɵba;
  _FormsModule_4:import5.FormsModule;
  _MATERIAL_SANITY_CHECKS_5:any;
  _CompatibilityModule_6:import6.CompatibilityModule;
  _MdCommonModule_7:import6.MdCommonModule;
  _PlatformModule_8:import6.PlatformModule;
  _ɵm_9:import6.ɵm;
  _MdRippleModule_10:import6.MdRippleModule;
  _MdSelectionModule_11:import6.MdSelectionModule;
  _MdOptionModule_12:import6.MdOptionModule;
  _PortalModule_13:import6.PortalModule;
  _OverlayModule_14:import6.OverlayModule;
  _MdAutocompleteModule_15:import6.MdAutocompleteModule;
  _StyleModule_16:import6.StyleModule;
  _MdButtonModule_17:import6.MdButtonModule;
  _MdButtonToggleModule_18:import6.MdButtonToggleModule;
  _MdCardModule_19:import6.MdCardModule;
  _MdChipsModule_20:import6.MdChipsModule;
  _MdCheckboxModule_21:import6.MdCheckboxModule;
  _A11yModule_22:import6.A11yModule;
  _MdDialogModule_23:import6.MdDialogModule;
  _MdDatepickerModule_24:import6.MdDatepickerModule;
  _MdLineModule_25:import6.MdLineModule;
  _MdGridListModule_26:import6.MdGridListModule;
  _MdIconModule_27:import6.MdIconModule;
  _MdInputModule_28:import6.MdInputModule;
  _MdListModule_29:import6.MdListModule;
  _MdMenuModule_30:import6.MdMenuModule;
  _MdProgressBarModule_31:import6.MdProgressBarModule;
  _MdProgressSpinnerModule_32:import6.MdProgressSpinnerModule;
  _MdRadioModule_33:import6.MdRadioModule;
  _MdSelectModule_34:import6.MdSelectModule;
  _MdSidenavModule_35:import6.MdSidenavModule;
  _RtlModule_36:import6.RtlModule;
  _MdSliderModule_37:import6.MdSliderModule;
  _MdSlideToggleModule_38:import6.MdSlideToggleModule;
  _MdSnackBarModule_39:import6.MdSnackBarModule;
  _ObserveContentModule_40:import6.ObserveContentModule;
  _MdTabsModule_41:import6.MdTabsModule;
  _MdToolbarModule_42:import6.MdToolbarModule;
  _MdTooltipModule_43:import6.MdTooltipModule;
  _MaterialModule_44:import6.MaterialModule;
  _Ng2PaginationModule_45:import7.Ng2PaginationModule;
  _ReactiveFormsModule_46:import5.ReactiveFormsModule;
  _ProductBatchModule_47:import1.ProductBatchModule;
  _ROUTES_48:any[];
  __NgLocalization_49:import4.NgLocaleLocalization;
  __ɵi_50:import5.ɵi;
  __Platform_51:import6.Platform;
  __ScrollDispatcher_52:any;
  __ɵo_53:any;
  __OverlayContainer_54:any;
  __ɵr_55:import6.ɵr;
  __Overlay_56:import6.Overlay;
  __FocusOriginMonitor_57:any;
  __UniqueSelectionDispatcher_58:any;
  __InteractivityChecker_59:import6.InteractivityChecker;
  __FocusTrapFactory_60:import6.FocusTrapFactory;
  __LiveAnnouncer_61:any;
  __MdDialog_62:import6.MdDialog;
  __MdDatepickerIntl_63:import6.MdDatepickerIntl;
  __MdIconRegistry_64:any;
  __HAMMER_GESTURE_CONFIG_65:import6.GestureConfig;
  __MdSnackBar_66:import6.MdSnackBar;
  __ɵa_67:import6.ɵa;
  __PaginationService_68:import8.PaginationService;
  __FormBuilder_69:import5.FormBuilder;
  __ProductBatchService_70:import9.ProductBatchService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import10.ProductBatchsAdminComponentNgFactory,
      import11.MdDialogContainerNgFactory,
      import11.MdDatepickerContentNgFactory,
      import11.MdSnackBarContainerNgFactory,
      import11.SimpleSnackBarNgFactory,
      import11.TooltipComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_49():import4.NgLocaleLocalization {
    if ((this.__NgLocalization_49 == null)) { (this.__NgLocalization_49 = new import4.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_49;
  }
  get _ɵi_50():import5.ɵi {
    if ((this.__ɵi_50 == null)) { (this.__ɵi_50 = new import5.ɵi()); }
    return this.__ɵi_50;
  }
  get _Platform_51():import6.Platform {
    if ((this.__Platform_51 == null)) { (this.__Platform_51 = new import6.Platform()); }
    return this.__Platform_51;
  }
  get _ScrollDispatcher_52():any {
    if ((this.__ScrollDispatcher_52 == null)) { (this.__ScrollDispatcher_52 = import6.ɵd(this.parent.get(import6.ScrollDispatcher,(null as any)),this.parent.get(import0.NgZone),this._Platform_51)); }
    return this.__ScrollDispatcher_52;
  }
  get _ɵo_53():any {
    if ((this.__ɵo_53 == null)) { (this.__ɵo_53 = import6.ɵp(this.parent.get(import6.ɵo,(null as any)),this._ScrollDispatcher_52)); }
    return this.__ɵo_53;
  }
  get _OverlayContainer_54():any {
    if ((this.__OverlayContainer_54 == null)) { (this.__OverlayContainer_54 = import6.ɵb(this.parent.get(import6.OverlayContainer,(null as any)))); }
    return this.__OverlayContainer_54;
  }
  get _ɵr_55():import6.ɵr {
    if ((this.__ɵr_55 == null)) { (this.__ɵr_55 = new import6.ɵr(this._ɵo_53)); }
    return this.__ɵr_55;
  }
  get _Overlay_56():import6.Overlay {
    if ((this.__Overlay_56 == null)) { (this.__Overlay_56 = new import6.Overlay(this._OverlayContainer_54,this.componentFactoryResolver,this._ɵr_55,this.parent.get(import0.ApplicationRef),this,this.parent.get(import0.NgZone))); }
    return this.__Overlay_56;
  }
  get _FocusOriginMonitor_57():any {
    if ((this.__FocusOriginMonitor_57 == null)) { (this.__FocusOriginMonitor_57 = import6.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY(this.parent.get(import6.FocusOriginMonitor,(null as any)),this.parent.get(import0.NgZone),this._Platform_51)); }
    return this.__FocusOriginMonitor_57;
  }
  get _UniqueSelectionDispatcher_58():any {
    if ((this.__UniqueSelectionDispatcher_58 == null)) { (this.__UniqueSelectionDispatcher_58 = import6.ɵh(this.parent.get(import6.UniqueSelectionDispatcher,(null as any)))); }
    return this.__UniqueSelectionDispatcher_58;
  }
  get _InteractivityChecker_59():import6.InteractivityChecker {
    if ((this.__InteractivityChecker_59 == null)) { (this.__InteractivityChecker_59 = new import6.InteractivityChecker(this._Platform_51)); }
    return this.__InteractivityChecker_59;
  }
  get _FocusTrapFactory_60():import6.FocusTrapFactory {
    if ((this.__FocusTrapFactory_60 == null)) { (this.__FocusTrapFactory_60 = new import6.FocusTrapFactory(this._InteractivityChecker_59,this.parent.get(import0.NgZone))); }
    return this.__FocusTrapFactory_60;
  }
  get _LiveAnnouncer_61():any {
    if ((this.__LiveAnnouncer_61 == null)) { (this.__LiveAnnouncer_61 = import6.ɵg(this.parent.get(import6.LiveAnnouncer,(null as any)),this.parent.get(import6.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)),this._Platform_51)); }
    return this.__LiveAnnouncer_61;
  }
  get _MdDialog_62():import6.MdDialog {
    if ((this.__MdDialog_62 == null)) { (this.__MdDialog_62 = new import6.MdDialog(this._Overlay_56,this,this.parent.get(import4.Location,(null as any)),this.parent.get(import6.MdDialog,(null as any)))); }
    return this.__MdDialog_62;
  }
  get _MdDatepickerIntl_63():import6.MdDatepickerIntl {
    if ((this.__MdDatepickerIntl_63 == null)) { (this.__MdDatepickerIntl_63 = new import6.MdDatepickerIntl()); }
    return this.__MdDatepickerIntl_63;
  }
  get _MdIconRegistry_64():any {
    if ((this.__MdIconRegistry_64 == null)) { (this.__MdIconRegistry_64 = import6.ICON_REGISTRY_PROVIDER_FACTORY(this.parent.get(import6.MdIconRegistry,(null as any)),this.parent.get(import12.Http,(null as any)),this.parent.get(import13.DomSanitizer))); }
    return this.__MdIconRegistry_64;
  }
  get _HAMMER_GESTURE_CONFIG_65():import6.GestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_65 == null)) { (this.__HAMMER_GESTURE_CONFIG_65 = new import6.GestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_65;
  }
  get _MdSnackBar_66():import6.MdSnackBar {
    if ((this.__MdSnackBar_66 == null)) { (this.__MdSnackBar_66 = new import6.MdSnackBar(this._Overlay_56,this._LiveAnnouncer_61,this.parent.get(import6.MdSnackBar,(null as any)))); }
    return this.__MdSnackBar_66;
  }
  get _ɵa_67():import6.ɵa {
    if ((this.__ɵa_67 == null)) { (this.__ɵa_67 = new import6.ɵa()); }
    return this.__ɵa_67;
  }
  get _PaginationService_68():import8.PaginationService {
    if ((this.__PaginationService_68 == null)) { (this.__PaginationService_68 = new import8.PaginationService()); }
    return this.__PaginationService_68;
  }
  get _FormBuilder_69():import5.FormBuilder {
    if ((this.__FormBuilder_69 == null)) { (this.__FormBuilder_69 = new import5.FormBuilder()); }
    return this.__FormBuilder_69;
  }
  get _ProductBatchService_70():import9.ProductBatchService {
    if ((this.__ProductBatchService_70 == null)) { (this.__ProductBatchService_70 = new import9.ProductBatchService(this.parent.get(import12.Http),this.parent.get(import14.ErrorService),this.parent.get(import15.ToastsManager),this.parent.get(import16.AuthService))); }
    return this.__ProductBatchService_70;
  }
  createInternal():import1.ProductBatchModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._ProductBatchRouting_1 = new import3.ProductBatchRouting();
    this._CommonModule_2 = new import4.CommonModule();
    this._ɵba_3 = new import5.ɵba();
    this._FormsModule_4 = new import5.FormsModule();
    this._MATERIAL_SANITY_CHECKS_5 = true;
    this._CompatibilityModule_6 = new import6.CompatibilityModule(this.parent.get(import13.DOCUMENT,(null as any)),this._MATERIAL_SANITY_CHECKS_5);
    this._MdCommonModule_7 = new import6.MdCommonModule();
    this._PlatformModule_8 = new import6.PlatformModule();
    this._ɵm_9 = new import6.ɵm();
    this._MdRippleModule_10 = new import6.MdRippleModule();
    this._MdSelectionModule_11 = new import6.MdSelectionModule();
    this._MdOptionModule_12 = new import6.MdOptionModule();
    this._PortalModule_13 = new import6.PortalModule();
    this._OverlayModule_14 = new import6.OverlayModule();
    this._MdAutocompleteModule_15 = new import6.MdAutocompleteModule();
    this._StyleModule_16 = new import6.StyleModule();
    this._MdButtonModule_17 = new import6.MdButtonModule();
    this._MdButtonToggleModule_18 = new import6.MdButtonToggleModule();
    this._MdCardModule_19 = new import6.MdCardModule();
    this._MdChipsModule_20 = new import6.MdChipsModule();
    this._MdCheckboxModule_21 = new import6.MdCheckboxModule();
    this._A11yModule_22 = new import6.A11yModule();
    this._MdDialogModule_23 = new import6.MdDialogModule();
    this._MdDatepickerModule_24 = new import6.MdDatepickerModule();
    this._MdLineModule_25 = new import6.MdLineModule();
    this._MdGridListModule_26 = new import6.MdGridListModule();
    this._MdIconModule_27 = new import6.MdIconModule();
    this._MdInputModule_28 = new import6.MdInputModule();
    this._MdListModule_29 = new import6.MdListModule();
    this._MdMenuModule_30 = new import6.MdMenuModule();
    this._MdProgressBarModule_31 = new import6.MdProgressBarModule();
    this._MdProgressSpinnerModule_32 = new import6.MdProgressSpinnerModule();
    this._MdRadioModule_33 = new import6.MdRadioModule();
    this._MdSelectModule_34 = new import6.MdSelectModule();
    this._MdSidenavModule_35 = new import6.MdSidenavModule();
    this._RtlModule_36 = new import6.RtlModule();
    this._MdSliderModule_37 = new import6.MdSliderModule();
    this._MdSlideToggleModule_38 = new import6.MdSlideToggleModule();
    this._MdSnackBarModule_39 = new import6.MdSnackBarModule();
    this._ObserveContentModule_40 = new import6.ObserveContentModule();
    this._MdTabsModule_41 = new import6.MdTabsModule();
    this._MdToolbarModule_42 = new import6.MdToolbarModule();
    this._MdTooltipModule_43 = new import6.MdTooltipModule();
    this._MaterialModule_44 = new import6.MaterialModule();
    this._Ng2PaginationModule_45 = new import7.Ng2PaginationModule();
    this._ReactiveFormsModule_46 = new import5.ReactiveFormsModule();
    this._ProductBatchModule_47 = new import1.ProductBatchModule();
        this._ROUTES_48 = [[{
          path: '',
          component: import17.ProductBatchsAdminComponent,
          canActivate: [import18.AdminGuardService]
        }
    ]];
    return this._ProductBatchModule_47;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.ProductBatchRouting)) { return this._ProductBatchRouting_1; }
    if ((token === import4.CommonModule)) { return this._CommonModule_2; }
    if ((token === import5.ɵba)) { return this._ɵba_3; }
    if ((token === import5.FormsModule)) { return this._FormsModule_4; }
    if ((token === import6.MATERIAL_SANITY_CHECKS)) { return this._MATERIAL_SANITY_CHECKS_5; }
    if ((token === import6.CompatibilityModule)) { return this._CompatibilityModule_6; }
    if ((token === import6.MdCommonModule)) { return this._MdCommonModule_7; }
    if ((token === import6.PlatformModule)) { return this._PlatformModule_8; }
    if ((token === import6.ɵm)) { return this._ɵm_9; }
    if ((token === import6.MdRippleModule)) { return this._MdRippleModule_10; }
    if ((token === import6.MdSelectionModule)) { return this._MdSelectionModule_11; }
    if ((token === import6.MdOptionModule)) { return this._MdOptionModule_12; }
    if ((token === import6.PortalModule)) { return this._PortalModule_13; }
    if ((token === import6.OverlayModule)) { return this._OverlayModule_14; }
    if ((token === import6.MdAutocompleteModule)) { return this._MdAutocompleteModule_15; }
    if ((token === import6.StyleModule)) { return this._StyleModule_16; }
    if ((token === import6.MdButtonModule)) { return this._MdButtonModule_17; }
    if ((token === import6.MdButtonToggleModule)) { return this._MdButtonToggleModule_18; }
    if ((token === import6.MdCardModule)) { return this._MdCardModule_19; }
    if ((token === import6.MdChipsModule)) { return this._MdChipsModule_20; }
    if ((token === import6.MdCheckboxModule)) { return this._MdCheckboxModule_21; }
    if ((token === import6.A11yModule)) { return this._A11yModule_22; }
    if ((token === import6.MdDialogModule)) { return this._MdDialogModule_23; }
    if ((token === import6.MdDatepickerModule)) { return this._MdDatepickerModule_24; }
    if ((token === import6.MdLineModule)) { return this._MdLineModule_25; }
    if ((token === import6.MdGridListModule)) { return this._MdGridListModule_26; }
    if ((token === import6.MdIconModule)) { return this._MdIconModule_27; }
    if ((token === import6.MdInputModule)) { return this._MdInputModule_28; }
    if ((token === import6.MdListModule)) { return this._MdListModule_29; }
    if ((token === import6.MdMenuModule)) { return this._MdMenuModule_30; }
    if ((token === import6.MdProgressBarModule)) { return this._MdProgressBarModule_31; }
    if ((token === import6.MdProgressSpinnerModule)) { return this._MdProgressSpinnerModule_32; }
    if ((token === import6.MdRadioModule)) { return this._MdRadioModule_33; }
    if ((token === import6.MdSelectModule)) { return this._MdSelectModule_34; }
    if ((token === import6.MdSidenavModule)) { return this._MdSidenavModule_35; }
    if ((token === import6.RtlModule)) { return this._RtlModule_36; }
    if ((token === import6.MdSliderModule)) { return this._MdSliderModule_37; }
    if ((token === import6.MdSlideToggleModule)) { return this._MdSlideToggleModule_38; }
    if ((token === import6.MdSnackBarModule)) { return this._MdSnackBarModule_39; }
    if ((token === import6.ObserveContentModule)) { return this._ObserveContentModule_40; }
    if ((token === import6.MdTabsModule)) { return this._MdTabsModule_41; }
    if ((token === import6.MdToolbarModule)) { return this._MdToolbarModule_42; }
    if ((token === import6.MdTooltipModule)) { return this._MdTooltipModule_43; }
    if ((token === import6.MaterialModule)) { return this._MaterialModule_44; }
    if ((token === import7.Ng2PaginationModule)) { return this._Ng2PaginationModule_45; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_46; }
    if ((token === import1.ProductBatchModule)) { return this._ProductBatchModule_47; }
    if ((token === import2.ROUTES)) { return this._ROUTES_48; }
    if ((token === import4.NgLocalization)) { return this._NgLocalization_49; }
    if ((token === import5.ɵi)) { return this._ɵi_50; }
    if ((token === import6.Platform)) { return this._Platform_51; }
    if ((token === import6.ScrollDispatcher)) { return this._ScrollDispatcher_52; }
    if ((token === import6.ɵo)) { return this._ɵo_53; }
    if ((token === import6.OverlayContainer)) { return this._OverlayContainer_54; }
    if ((token === import6.ɵr)) { return this._ɵr_55; }
    if ((token === import6.Overlay)) { return this._Overlay_56; }
    if ((token === import6.FocusOriginMonitor)) { return this._FocusOriginMonitor_57; }
    if ((token === import6.UniqueSelectionDispatcher)) { return this._UniqueSelectionDispatcher_58; }
    if ((token === import6.InteractivityChecker)) { return this._InteractivityChecker_59; }
    if ((token === import6.FocusTrapFactory)) { return this._FocusTrapFactory_60; }
    if ((token === import6.LiveAnnouncer)) { return this._LiveAnnouncer_61; }
    if ((token === import6.MdDialog)) { return this._MdDialog_62; }
    if ((token === import6.MdDatepickerIntl)) { return this._MdDatepickerIntl_63; }
    if ((token === import6.MdIconRegistry)) { return this._MdIconRegistry_64; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_65; }
    if ((token === import6.MdSnackBar)) { return this._MdSnackBar_66; }
    if ((token === import6.ɵa)) { return this._ɵa_67; }
    if ((token === import8.PaginationService)) { return this._PaginationService_68; }
    if ((token === import5.FormBuilder)) { return this._FormBuilder_69; }
    if ((token === import9.ProductBatchService)) { return this._ProductBatchService_70; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ProductBatchModuleNgFactory:import0.NgModuleFactory<import1.ProductBatchModule> = new import0.NgModuleFactory<any>(ProductBatchModuleInjector,import1.ProductBatchModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FsYW4vYXBwL2FsZXMvc2Fsb24vc3JjL2FwcC9wcm9kdWN0QmF0Y2gvcHJvZHVjdEJhdGNoLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hbGFuL2FwcC9hbGVzL3NhbG9uL3NyYy9hcHAvcHJvZHVjdEJhdGNoL3Byb2R1Y3RCYXRjaC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
