/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/router';
import * as import2 from '../../../../src/app/product/product.component';
const styles_ProductComponent:any[] = ([] as any[]);
export const RenderType_ProductComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ProductComponent,
  data: {}
}
);
export function View_ProductComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(8388608,(null as any),(null as any),1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    import0.ɵdid(73728,(null as any),0,import1.RouterOutlet,[
      import1.RouterOutletMap,
      import0.ViewContainerRef,
      import0.ComponentFactoryResolver,
      [
        8,
        (null as any)
      ]

    ]
    ,(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_ProductComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-product',([] as any[]),(null as any),(null as any),(null as any),View_ProductComponent_0,RenderType_ProductComponent)),
    import0.ɵdid(57344,(null as any),0,import2.ProductComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ProductComponentNgFactory:import0.ComponentFactory<import2.ProductComponent> = import0.ɵccf('app-product',import2.ProductComponent,View_ProductComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FsYW4vYXBwL2FsZXMvc2Fsb24vc3JjL2FwcC9wcm9kdWN0L3Byb2R1Y3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FsYW4vYXBwL2FsZXMvc2Fsb24vc3JjL2FwcC9wcm9kdWN0L3Byb2R1Y3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYWxhbi9hcHAvYWxlcy9zYWxvbi9zcmMvYXBwL3Byb2R1Y3QvcHJvZHVjdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FsYW4vYXBwL2FsZXMvc2Fsb24vc3JjL2FwcC9wcm9kdWN0L3Byb2R1Y3QuY29tcG9uZW50LnRzLlByb2R1Y3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XG4iLCI8YXBwLXByb2R1Y3Q+PC9hcHAtcHJvZHVjdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO2dCQUFBOzs7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUErQjs7Ozs7O0lDQS9CO2dCQUFBOzs7SUFBQTs7OyJ9
