/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.phyto-topnav[_ngcontent-%COMP%] {\n    height: 100% !important;\n    background-color: #efe9df !important;\n}\n.done[_ngcontent-%COMP%], .pas-done[_ngcontent-%COMP%] {\n    margin: 0 0 15px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FsYW4vYXBwL2FsZXMvc2Fsb24vc3JjL2FwcC91c2VyL2FjY291bnRSZWNvdmVyL3Jlc2V0UGFnZXNTdHlsZS5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYWxhbi9hcHAvYWxlcy9zYWxvbi9zcmMvYXBwL3VzZXIvYWNjb3VudFJlY292ZXIvZm9yZ2V0UGFzc3dvcmQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
