/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.crrt-win[_ngcontent-%COMP%] {\n    padding: 15px;\n}\n.crrt-win[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {\n    text-align: center;\n}\n.crrt-wincnt[_ngcontent-%COMP%] {\n    max-width: 250px;\n    margin: 0 auto;\n    padding: 10px 10px 5px;\n}\n.crrt-winpic[_ngcontent-%COMP%] {\n    padding: 15px;\n    height: 224px;\n}\n.done[_ngcontent-%COMP%] {\n    width: 100%;\n    margin: 15px 0;\n    padding: 15px !important;\n}\n.prevwin[_ngcontent-%COMP%] {\n    padding: 15px;\n}\na.follow[_ngcontent-%COMP%] {\n    margin-top: 15px;\n}\n.follow[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n    color: indianred;\n    float: left;\n    max-width: 75%;\n}\n.follow[_ngcontent-%COMP%]   img[_ngcontent-%COMP%] {\n    width: 50px;\n    float: left;\n}\n\n\n\n@media screen and (min-width: 494px) {\n\n.follow[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n    margin: 15px 0;\n}\n}\n\n@media screen and (max-width: 493px) {\n\n.follow[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {\n    margin: 5px;\n}\n}\n\n@media screen and (min-width: 746px) {\n.prevwin-pics[_ngcontent-%COMP%] {\n    height: 350px;\n}\n}\n\n@media screen and (min-width: 572px) and (max-width: 745px) {\n.prevwin-pics[_ngcontent-%COMP%] {\n    height: 440px;\n}\n}\n\n@media screen and (min-width: 381px) and (max-width: 571px) {\n.prevwin-pics[_ngcontent-%COMP%] {\n    height: 700px;\n}\n}\n\n@media screen and (max-width: 380px) {\n.prevwin-pics[_ngcontent-%COMP%] {\n    height: 1400px;\n}\n}'];
//# sourceMappingURL=social.component.css.shim.ngstyle.js.map