/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
/* tslint:disable */
/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */ export var styles = ['.phyto-menu[_ngcontent-%COMP%] {\r\n  max-width: 950px;\r\n  margin: 0 auto;\r\n  height: 100% !important;\r\n}\r\n.phyto-sidenav[_ngcontent-%COMP%] {\r\n  box-shadow: none !important;\r\n  bottom: initial !important;\r\n}'];
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map