/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/promotion/promotionDeleteDialog.component';
import * as import2 from '@angular/material';
const styles_PromotionDeleteDialog:any[] = ([] as any[]);
export const RenderType_PromotionDeleteDialog:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PromotionDeleteDialog,
  data: {}
}
);
export function View_PromotionDeleteDialog_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),10,'div',[[
        'class',
        'areusure'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',[[
        'style',
        'max-width: 280px;'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['This action is not reversible. Are you sure you want to delete?'])),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',[
      [
        'class',
        'justkd'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.PromotionDeleteDialog = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.dialogRefDelete.close('')) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Cancel'])),
    (l()(),import0.ɵted((null as any),['\n  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',[
      [
        'class',
        'dltfrv'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.PromotionDeleteDialog = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.dialogRefDelete.close('delete')) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Delete'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_PromotionDeleteDialog_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'promotionDeleteDialog',([] as any[]),(null as any),(null as any),(null as any),View_PromotionDeleteDialog_0,RenderType_PromotionDeleteDialog)),
    import0.ɵdid(24576,(null as any),0,import1.PromotionDeleteDialog,[import2.MdDialogRef],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const PromotionDeleteDialogNgFactory:import0.ComponentFactory<import1.PromotionDeleteDialog> = import0.ɵccf('promotionDeleteDialog',import1.PromotionDeleteDialog,View_PromotionDeleteDialog_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FsYW4vYXBwL2FsZXMvc2Fsb24vc3JjL2FwcC9wcm9tb3Rpb24vcHJvbW90aW9uRGVsZXRlRGlhbG9nLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9hbGFuL2FwcC9hbGVzL3NhbG9uL3NyYy9hcHAvcHJvbW90aW9uL3Byb21vdGlvbkRlbGV0ZURpYWxvZy5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9hbGFuL2FwcC9hbGVzL3NhbG9uL3NyYy9hcHAvcHJvbW90aW9uL3Byb21vdGlvbkRlbGV0ZURpYWxvZy5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FsYW4vYXBwL2FsZXMvc2Fsb24vc3JjL2FwcC9wcm9tb3Rpb24vcHJvbW90aW9uRGVsZXRlRGlhbG9nLmNvbXBvbmVudC50cy5Qcm9tb3Rpb25EZWxldGVEaWFsb2dfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiYXJldXN1cmVcIj5cbiAgPHAgc3R5bGU9XCJtYXgtd2lkdGg6IDI4MHB4O1wiPlRoaXMgYWN0aW9uIGlzIG5vdCByZXZlcnNpYmxlLiBBcmUgeW91IHN1cmUgeW91IHdhbnQgdG8gZGVsZXRlPzwvcD5cbiAgPGJ1dHRvbiB0eXBlPVwiYnV0dG9uXCIgY2xhc3M9XCJqdXN0a2RcIiAoY2xpY2spPVwiZGlhbG9nUmVmRGVsZXRlLmNsb3NlKCcnKVwiPkNhbmNlbDwvYnV0dG9uPlxuICA8YnV0dG9uIHR5cGU9XCJidXR0b25cIiBjbGFzcz1cImRsdGZydlwiIChjbGljayk9XCJkaWFsb2dSZWZEZWxldGUuY2xvc2UoJ2RlbGV0ZScpXCI+RGVsZXRlPC9idXR0b24+XG48L2Rpdj5cbiIsIjxwcm9tb3Rpb25EZWxldGVEaWFsb2c+PC9wcm9tb3Rpb25EZWxldGVEaWFsb2c+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXNCO01BQ3BCO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBNkI7SUFBbUU7SUFDaEc7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQXFDO1FBQUE7UUFBQTtNQUFBO01BQXJDO0lBQUE7SUFBeUU7SUFBZTtJQUN4RjtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO01BQUE7TUFBcUM7UUFBQTtRQUFBO01BQUE7TUFBckM7SUFBQTtJQUErRTtJQUFlO0lBQzFGOzs7Ozs7SUNKTjtnQkFBQTs7OzsifQ==
